name: Publish
on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        name: "Publish"
        runs-on: windows-latest
        environment: production
        steps:                    
            - name: Download workflow artifact          
              uses: dawidd6/action-download-artifact@v3.1.2
              with:
                    name: 'tool-package'
                    workflow_conclusion: success
                    workflow: pr.yml
                    workflow_search: true
                    # commit: ${{github.event.push.after}}
              
            - name: dotnet publish
              run: dotnet nuget push "**/*.nupkg" --api-key ${{secrets.NUGET_KEY}}  --source "https://www.nuget.org/packages/Gport.UpgradeAllProjects"
            