name: Publish
on:
    push:
        branches:
            - main

jobs:
    build:
        name: "Publish"
        runs-on: windows-latest
        environment: production
        steps:                    
            - name: Download workflow artifact          
              uses: dawidd6/action-download-artifact@v3.1.2
              with:
                    workflow_conclusion: success
                    workflow: pr.yml
                    workflow_search: true                    
              
            - name: dotnet pack
              run: dotnet nuget push ./nupkg --api-ket ${{secrets.NUGET_KEY}}
            